export const SPLITWISE_USER = "SPLITWISE_USER";
export const SPLITWISE_FRIENDS = "SPLITWISE_FRIENDS";
export const SPLITWISE_EXPENCES = "SPLITWISE_EXPENCES";

export const ADD_FRIEND_REQUEST = "ADD_FRIEND_REQUEST";
export const ADD_FRIEND_FAILED = "ADD_FRIEND_FAILED";
export const ADD_FRIEND_SUCCESS = "ADD_FRIEND_SUCCESS";

export const GET_FRIENDS_REQUEST = "GET_FRIENDS_REQUEST";
export const GET_FRIENDS_FAILED = "GET_FRIENDS_FAILED";
export const GET_FRIENDS_SUCCESS = "GET_FRIENDS_SUCCESS";

export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_FAILED = "GET_USER_FAILED";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";

export const ADD_EXPENCES_REQUEST = "ADD_EXPENCES_REQUEST";
export const ADD_EXPENCES_SUCCESS = "ADD_EXPENCES_SUCCESS";
export const ADD_EXPENCES_FAILED = "ADD_EXPENCES_FAILED";
