export const SPLITWISE_FRIENDS = "SPLITWISE_FRIENDS";
export const ADD_FRIEND_REQUEST = "ADD_FRIEND_REQUEST";
export const ADD_FRIEND_FAILED = "ADD_FRIEND_FAILED";
export const ADD_FRIEND_SUCCESS = "ADD_FRIEND_SUCCESS";

export const GET_FRIENDS_REQUEST = "GET_FRIENDS_REQUEST";
export const GET_FRIENDS_FAILED = "GET_FRIENDS_FAILED";
export const GET_FRIENDS_SUCCESS = "GET_FRIENDS_SUCCESS";
